---
- name: Запуск fio теста {{ fio_test_name }}
  hosts: all
  become: true

  vars:
    fio_test_name: "benchmark_sr_1M_qd32_j4"
    fio_test_disk: "nvme0n1"
    fio_output_dir: "/tmp/fio_results"
    fio_readwrite: "read"
    fio_runtime: 60
    fio_size: "1200G"
    fio_bs: "1M"
    fio_iodepth: 32
    fio_numjobs: 4

  pre_tasks:
    - name: Получить текущее время
      command: date +%Y%m%d_%H%M%S
      register: time_output
      delegate_to: localhost
      run_once: true
      become: false

    - name: Установить переменную времени
      set_fact:
        current_time: "{{ time_output.stdout }}"

  tasks:
    - name: Проверка наличия fio на сервере
      command: which fio
      register: fio_check
      ignore_errors: true
      changed_when: false

    - name: Получить строку с информацией о диске {{ fio_test_disk }}
      shell: lsblk -o NAME,SIZE | grep "^{{ fio_test_disk }}"
      register: fio_disk_info
      changed_when: false

    - name: Проверить, содержит ли диск размер 3.5T
      set_fact:
        fio_device_is_3_5T: "{{ '3.5T' in fio_disk_info.stdout }}"

    - name: Пропустить тест, если размер не 3.5T
      debug:
        msg: "Размер диска {{ fio_test_disk }} не равен 3.5T, тест будет пропущен."
      when: not fio_device_is_3_5T

    - name: Установка fio при необходимости
      package:
        name: fio
        state: present
      when: fio_check.rc != 0

    - name: Создание директории для результатов
      file:
        path: "{{ fio_output_dir }}"
        state: directory
        mode: "0755"

    - name: Запуск тестов fio
      shell: >
        fio --filename=/dev/{{ fio_test_disk }}
        --direct=1
        --bs={{ fio_bs }}
        --ioengine=libaio
        --iodepth={{ fio_iodepth }}
        --size={{ fio_size }}
        --runtime={{ fio_runtime }}
        --numjobs={{ fio_numjobs }}
        --time_based
        --group_reporting
        --name={{ fio_test_name }}
        --readwrite={{ fio_readwrite }}
        --output={{ fio_output_dir }}/fio_results_{{ inventory_hostname }}_{{ current_time }}.txt
      async: 1800
      poll: 0
      register: fio_async_result

    - name: Проверка статуса выполнения fio
      async_status:
        jid: "{{ fio_async_result.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 180
      delay: 10

    - name: Получение результатов тестов
      fetch:
        src: "{{ fio_output_dir }}/fio_results_{{ inventory_hostname }}_{{ current_time }}.txt"
        dest: "../fio_results/{{ inventory_hostname }}/"
        flat: yes

    - name: Вывод пути к результатам
      debug:
        msg: "Результаты теста сохранены в ../fio_results/{{ inventory_hostname }}/fio_results_{{ inventory_hostname }}_{{ current_time }}.txt"
