---
- name: Istalling FIO on hosts
  hosts: fio_test  # groups for hosts on which FIO will be installed
  become: true  # use sudo

  tasks:
    - name: Updating packetges (for Debian/Ubuntu)
      ansible.builtin.apt:
        update_cache: true
      when: ansible_os_family == "Debian"

    - name: Installing fio (Debian/Ubuntu)
      ansible.builtin.apt:
        name: fio
        state: present
      when: ansible_os_family == "Debian"

    - name: Installing fio (RedHat/CentOS)
      ansible.builtin.yum:
        name: fio
        state: present
      when: ansible_os_family == "RedHat"

    - name: Checking installed fio
      ansible.builtin.command: fio --version
      register: fio_version
      changed_when: false

    - name: Output fio version
      ansible.builtin.debug:
        msg: "Installed FIO version: {{ fio_version.stdout }}"
